apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "select"
      name: "postType"
      id: "postType"
      key: "postType"
      value: "standard"
      label: "文章形式"
      options:
        - label: 标准
          value: "standard"
        - label: 标准
          value: "status"

          


