apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-farallon
spec:
  displayName: Farallon
  author:
    name: 困困鱼
    website: https://github.com/chengzhongxue
  customTemplates:
    category:
      - name: 图片分类
        description: 
        screenshot:
        file: category-travel.html
  description: Farallon是一个简单的单列halo主题，具有完美的性能和优雅的设计
  logo: /themes/theme-farallon/assets/images/favicon.png
  homepage: https://github.com/chengzhongxue/halo-theme-farallon
  repo: https://github.com/chengzhongxue/halo-theme-farallon
  issues: https://github.com/chengzhongxue/halo-theme-farallon/issues
  settingName: "theme-farallon-setting"
  configMapName: "theme-farallon-configMap"
  version: 1.0.0
  requires: ">=2.15.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/theme-vite-starter/blob/main/LICENSE"
